FROM node:11.4.0-slim
ARG BASE_URL
ARG DB_URL
ARG ACCESS_KEY_ID
ARG SECRET_ACCESS_KEY_ID
WORKDIR /app
COPY package*.json ./
RUN npm install --quiet
COPY . .
RUN npm rebuild
RUN npm run build
EXPOSE 80
ENV HOST 0.0.0.0
ENV BASE_URL $BASE_URL
ENV DB_URL $DB_URL
ENV ACCESS_KEY_ID $ACCESS_KEY_ID
ENV SECRET_ACCESS_KEY_ID $SECRET_ACCESS_KEY_ID
CMD ["npm", "run", "start"]